version: '2'

networks:
  ORG__NAME_net:
    external: true

services:
  kafka0.ORG__NAME.com:
    container_name: kafka0.ORG__NAME.com
    image: hyperledger/fabric-kafka:0.4.15
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1

      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.ORG__NAME.com:2181,zookeeper1.ORG__NAME.com:2181,zookeeper2.ORG__NAME.com:2181
      
      # Replica setting
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=4
    # ports:
    #   - 9092:9092
    volumes:
      - ./volume:/tmp/kafka-logs
    networks:
      - ORG__NAME_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
