Organizations:
  - &NEW_ORG
    Name: NEW_ORG
    ID: NEW_ORGMSP
    MSPDir: ../../certs/NEW_ORG_LOWER.com/msp

    AnchorPeers:
    - Host: peer0.NEW_ORG_LOWER.com
      Port: 7051

Capabilities:
  Application: &ApplicationCapabilities
    V1_2: true
Application: &ApplicationConfig
  Organizations:

Profiles:
  DefaultChannel:
    Consortium: NEW_ORGConsortium
    Application:
      <<: *ApplicationConfig
      Organizations:
        - *NEW_ORG
      Capabilities:
        <<: *ApplicationCapabilities

